# cluster specific values
cluster:
  # specify cluster name
  name: equinix-cluster

  # specify cluster labels
  labels: {}

  # specify cluster annotations
  annotations: {}

# specify cloud credential secret name, do not need to be provided if using custom driver
cloudCredentialSecretName: ""

kubernetesVersion: ""

# general RKE options
rke:
  # enable local auth endpoint
  localClusterAuthEndpoint:
    enabled: false
    # specify fqdn of local access endpoint
    fqdn: ""
    # specify cacert of local access endpoint
    caCerts: ""

# specify user principal ids to be assiged as cluster members
# clusterMembers:
# - principalName: "local://u-z8zl5"
#   roleTemplateName: "cluster-member"

# Specify nodepool options. Can add multiple node groups, specify etcd, controlplane and worker roles.
nodepools:
- etcd: true
  controlplane: true
  worker: true

  # specify node labels
  labels: {}

  # specify node taints
  taints: {}

  # specify nodepool size
  quantity: 1

  # specify displayName
  displayName: ""

  # specify nodepool name
  name: equinix-nodepool-1

  billingCycle: hourly
  facilityCode: am6
  hwReservationId: ""
  os: ubuntu_20_04
  plan: c3.small.x86
  projectId: ""
  spotInstance: false
  spotPriceMax: ""
  terminationTime: ""
  userdata: ""
  machineDeploymentLabels: {}
  machineDeploymentAnnotations: {}

agentEnvs: []