apiVersion: v1
name: rancher-aws-cluster-template
description: RKE2 Cluster template for AWS
version: 0.2.0
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/512px-Amazon_Web_Services_Logo.svg.png
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default