{{- $clustername := .Values.cluster.name }}
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  {{- if .Values.cluster.labels }}
  labels:
{{ toYaml .Values.cluster.labels | indent 4 }}
  {{- end }}
  {{- if .Values.cluster.annotations }}
  annotations:
{{ toYaml .Values.cluster.annotations | indent 4 }}
  {{- end }}
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  {{- if .Values.cloudCredentialSecretName }}
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  {{- end }}
  {{- if .Values.kubernetesVersion }}
  kubernetesVersion: {{ .Values.kubernetesVersion }}
  {{- end }}
  rkeConfig:
    machinePools:
    {{- if .Values.nodepools }} {{ range $index, $nodepool := .Values.nodepools }}
    - controlPlaneRole: {{ $nodepool.controlplane }}
      etcdRole: {{ $nodepool.etcd }}
      workerRole: {{ $nodepool.worker }}
      quantity: {{ $nodepool.quantity }}
      name: {{ $clustername }}-{{ $nodepool.name }}
      machineConfigRef:
        kind: PacketConfig
        name: {{ $clustername }}-{{ $nodepool.name }}
      paused: false
      displayName: {{ $nodepool.displayName }}
      {{- if $nodepool.machineDeploymentLabels }}
      machineDeploymentLabels:
{{ toYaml $nodepool.machineDeploymentLabels | indent 8 }}
      {{- end }}
      {{- if $nodepool.machineDeploymentAnnotations }}
      machineDeploymentAnnotations:
{{ toYaml $nodepool.machineDeploymentAnnotations | indent 8 }}
      {{- end }}
      {{- end }}
    {{- end }}
    machineGlobalConfig:
      cni: calico
    {{- if .Values.rke.localClusterAuthEndpoint.enabled }}
    localClusterAuthEndpoint:
      enabled: {{ .Values.rke.localClusterAuthEndpoint.enabled }}
      fqdn: {{ .Values.rke.localClusterAuthEndpoint.fqdn }}
      caCerts: {{ .Values.rke.localClusterAuthEndpoint.caCerts }}
    {{- end }}
    upgradeStrategy:
      controlPlaneDrainOptions:
        enabled: false
      workerDrainOptions:
        enabled: false
      workerConcurrency: "10%"
      controlPlaneConcurrency: "10%"
{{- if .Values.agentEnvs }}
  agentEnvVars:
{{ toYaml .Values.agentEnvs | indent 4 }}
{{- end }}